Feature/begrep import
Informasjonsforvaltning/concept-catalogue-gui pull request #237
Opened 2020-11-16 07:52 UTC by hconhegg

2020-11-16 08:14 UTC, oyvindis commented on src/config.ts
> +env.REGISTRATION_HOST = 'https://registrering.staging.fellesdatakatalog.digdir.no';
Uncomment kun for lokal host, du må reverte alle endringer i denne filen.

2020-11-16 08:21 UTC, oyvindis requested changes
Se kommentar om config. I tillegg kan du squashe alle commits, de henger sammen på ny feature. Så kan du ha en commit melding for hele, f.eks. "feat: add concept import"

2020-11-16 09:08 UTC, azaxarov requested changes

2020-11-16 09:08 UTC, azaxarov commented on src/app/reducers/conceptMapper.ts
> +  const returnObj = {};
Prøv å unngå sånne meningsløse navn på variabler og heller bruk f.eks `.reduce`funksjon

2020-11-16 09:08 UTC, azaxarov commented on src/app/reducers/conceptMapper.ts
> +}
Disse funksjoner virker unødvendig. Se på spread syntaks: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2020-11-16 09:08 UTC, azaxarov commented on src/app/reducers/conceptMapper.ts
> +  };
Dette kan forenkles til en statement

2020-11-16 09:08 UTC, azaxarov commented on src/app/reducers/conceptMapper.ts
> +  };
Dette kan forenkles til en statement

2020-11-16 09:08 UTC, azaxarov commented on src/app/reducers/conceptMapper.ts
> +}
Det bør være en bedre måte å gjøre dette på

2020-11-16 09:08 UTC, azaxarov commented on src/app/reducers/conceptMapper.ts
> +  mergeIfExists(mapSeOgsaa(csvMap), mergedObject);
Det må være en bedre måte å gjøre dette på

2020-11-16 12:27 UTC, hconhegg commented on src/api/concept-catalogue-api.ts
> +import { Concept } from '../domain/Concept';
Hvorfor det? jeg bruker Concepts.

2020-11-16 12:52 UTC, azaxarov commented on src/api/concept-catalogue-api.ts
> +import { Concept } from '../domain/Concept';
Jeg vet, men hvis du ser på diffen, så har importen byttet linje fra 4 til 6. Det mener jeg er unødvendig siden det ikke er noe ny funksjonalitet.

2020-11-19 09:29 UTC, hconhegg commented on src/api/concept-catalogue-api.ts
> +import { Concept } from '../domain/Concept';
Ah, det var intellij/eslint som bytta på de.

2020-11-19 09:44 UTC, hconhegg commented on src/app/reducers/conceptMapper.ts
> +    [returnObj[spraak]] = data;
For fler-språkelige verdier hvor det bare kan være en verdi på ett språk, så går jeg gjennom hvert språk hvor det er garantert å være en verdi om nøkkelen eksisterer. så klager eslint på at jeg sier returnObj[spraak] = data[0] og vil ha destructuring.

2020-11-19 10:41 UTC, hconhegg commented on src/app/reducers/conceptMapper.ts
> +  const map = new Map<string, string[]>();
Ikke egentlig. Bare det jeg er kjent med.

2020-11-19 10:44 UTC, hconhegg commented on src/app/reducers/conceptMapper.ts
> +  const returnObj = {};
Hvordan ville du brukt reduce på map her?

2020-11-19 10:49 UTC, hconhegg commented on src/app/reducers/conceptMapper.ts
> +}
mergeIfExistsToPath er nødvendig. MergeIfExists var unødvendig.

2020-11-19 10:53 UTC, hconhegg commented on src/app/reducers/conceptMapper.ts
> +  };
Jeg ser ikke hvordan.

2020-11-24 09:56 UTC, azaxarov requested changes

2020-11-24 09:56 UTC, azaxarov commented on src/config.ts
> +env.SEARCH_FULLTEXT_HOST = 'https://search.staging.fellesdatakatalog.digdir.no';
Endringer i denne filen skal ikke kommittes

2020-11-24 09:56 UTC, azaxarov commented on src/pages/concept-registration-page/form-concept/form-concept.component.tsx
> +//  Feil ved import av fil. Teknisk feilmelding: lodash_get__WEBPACK_IMPORTED_MODULE_1___default()(...) is undefined
Fjern kommentar

2020-11-25 11:41 UTC, azaxarov approved these changes

2020-11-27 10:53 UTC, merged