Feat/mjs/concept search
Informasjonsforvaltning/concept-catalogue-gui pull request #276
Opened 2021-06-08 07:27 UTC by matsjs

Closes #274

2021-06-08 12:26 UTC, NilsOveTen approved these changes

2021-06-08 13:28 UTC, oyvindis commented on src/components/search-bar/styled.ts
> +  width: 50%;
Det er bedre hvis du ikke angir 'width' her, men setter flex-basis på elementet i flexbox.

2021-06-08 13:30 UTC, oyvindis commented on src/components/search-bar/styled.ts
> +  flex: 1 1;
Hvis du dropper 'width' i parent-element, så kan du her si ikke lov til grow og flex-basis 50%, slik:
flex: 0 0 50%;

2021-06-09 05:44 UTC, oyvindis commented on src/components/with-concepts/index.tsx
> +  conceptSuggestions: Concept[];
Endre til 'concepts'

2021-06-09 05:47 UTC, oyvindis commented on src/components/with-concepts/redux/reducer.ts
> +  conceptSuggestions: [],
Denne bør bare hete 'concepts' i hoc. Kan heller rename prop i komponenten der den brukes hvis det gir bedre mening der at den heter noe annet.

2021-06-09 05:53 UTC, oyvindis commented on src/redux/configureStore.js
> +    persistState(['featureToggle', 'settings'], { key: 'redux' })
Jeg tror ikke du trenger alt dette? Kan du gjøre den enklere, f.eks. slik:

import { applyMiddleware, createStore } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import createSagaMiddleware from 'redux-saga';

import RootReducer from './reducer';
import RootSaga from './saga';

const sagaMiddleware = createSagaMiddleware({
  context: {}
});

const store = createStore(
  RootReducer,
  composeWithDevTools(applyMiddleware(sagaMiddleware))
);

sagaMiddleware.run(RootSaga);

(module as any).host?.accept();

export default store;

2021-06-09 05:55 UTC, oyvindis commented on src/redux/configureStore.js
> +    persistState(['featureToggle', 'settings'], { key: 'redux' })
Da er det også noen dependencies i package.json du kan fjerne, blant annet redux-thunk, redux-localstorage, redux-api-middleware, redux-logger

2021-06-09 05:55 UTC, oyvindis commented on src/redux/fetchActions.js
> +export function fetchActions(url, types) {
Denne brukes ikke som jeg kan se.

2021-06-09 06:18 UTC, oyvindis requested changes
Se kommentarer.

Egentlig er en egen hoc litt overkill her synes jeg. Skal vel bare filtrere blant de begrepene som hentes i init-funksjonen i 'concept-list-page-pure' fra før. Nå hentes disse begrepene to ganger, både til hoc og til opprinnelig liste.

Er det verdt å ta med redux-biblioteket for dette, det er ganske stort.

2021-06-15 14:38 UTC, matsjs commented
Erstattes av https://github.com/Informasjonsforvaltning/concept-catalogue-gui/pull/277

2021-06-15 14:38 UTC, closed without merging