feat: adds demo logo
Informasjonsforvaltning/concept-catalogue-gui pull request #321
Opened 2021-11-18 15:43 UTC by matsjs

Part of Informasjonsforvaltning/fdk-admin-gui#108

2021-11-18 16:26 UTC, oyvindis commented on src/config.ts
> +env.REGISTRATION_HOST =
Lokale overrides må kommenteres ut.

2021-11-18 16:31 UTC, oyvindis requested changes
se kommentar.

2021-11-19 11:29 UTC, jeffreiffers approved these changes

2021-11-19 12:15 UTC, oyvindis approved these changes

2021-11-19 12:16 UTC, merged